### ISSUE TITLE
这里错了吧

### ISSUE THREAD

**Issue by chennian32** [AllentDan/LibtorchDetection#8]
https://github.com/AllentDan/LibtorchDetection/blob/a6c7d4908ca29082813c73b7a468ac23a2c4e733/src/models/yolo_training.cpp#L254

**Comment by AllentDan** [comment]
why？

**Comment by chennian32** [comment]
https://github.com/AllentDan/LibtorchDetection/blob/a6c7d4908ca29082813c73b7a468ac23a2c4e733/src/models/yolo_training.cpp#L355  和这里不一样

**Comment by AllentDan** [comment]
原版的 yolov4 tiny 就是这么处理的。[相关 issue](https://github.com/bubbliiiing/yolov4-tiny-pytorch/issues/31)
